### ISSUE TITLE
Please fix all the compilation errors for Raytracing Shader "RaytracingAreaShadows"!

### ISSUE THREAD

**Issue by Wenzy--** [Unity-Technologies/Unity-Experimental-DXR#9]
Hi,I have already downloaded the whole file include the LFS.And I can create a new project successfully.But when i rebuilt and run the project.It shows 

"Please fix all the compilation errors for Raytracing Shader "RaytracingAreaShadows"!"

and a caution said"GarbageCollector disposing of ComputeBuffer allocated in E:\UniyProject\[4]RTX\rtx3\SRP\com.unity.render-pipelines.high-definition\Runtime\Lighting\Shadow\HDShadowManager.cs at line 197. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
UnityEngine.ComputeBuffer:Finalize()
"
I can see all the object in the scene just can't see any rtx effect.Even though i have tried all the toggle button~

Win10 - RTX2080maxq

**Comment by TianZhongJun** [comment]
I met this problem too.
I change windows version.
then it is ok.
I use this:http://igetintopc.com/windows-10-x64-rs5-october-2018-free-download/

**Comment by ArnoldCarterWong** [comment]
I have this error too and was in 1903, still got this error after downgrading to 1809. Maybe I should try a clean new Win10 RS5 install

**Comment by ArnoldCarterWong** [comment]
I am using a rtx2070.
Some .raytrace shaders can't compile at all due to they can't include BSDF.hlsl and ImageBasedLighting.hlsl from SRP core's ShaderLibrary folder


One of the console error, the BSDF.hlsl does exist, also the unity editor crashes every time right after creating the project or reimporting all the stuffs:

Shader error in 'RaytracingIndirectDiffuse.raytrace': Compilation failed [0x80004005 - Unknown error.] 'HLSLSource:14:10: fatal error: 'Packages/com.unity.render-pipelines.core/ShaderLibrary/BSDF.hlsl' file not found
#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/BSDF.hlsl"

**Comment by Wenzy--** [comment]
Which version do u use before u install this package?I am already Windows 10 Home x64(1890 - OS17763.379)

**Comment by Wenzy--** [comment]
> Which version do u use before u install this package?I am already Windows 10 Home x64(1890 - OS17763.379)



> I am using a rtx2070.
> Some .raytrace shaders can't compile at all due to they can't include BSDF.hlsl and ImageBasedLighting.hlsl from SRP core's ShaderLibrary folder
> One of the console error, the BSDF.hlsl does exist, also the unity editor crashes every time right after creating the project or reimporting all the stuffs:
> Shader error in 'RaytracingIndirectDiffuse.raytrace': Compilation failed [0x80004005 - Unknown error.] 'HLSLSource:14:10: fatal error: 'Packages/com.unity.render-pipelines.core/ShaderLibrary/BSDF.hlsl' file not found
> #include "Packages/com.unity.render-pipelines.core/ShaderLibrary/BSDF.hlsl"

**Comment by Wenzy--** [comment]
> I met this problem too.
> I change windows version.
> then it is ok.
> I use this:http://igetintopc.com/windows-10-x64-rs5-october-2018-free-download/

Which version do u use before u install this package?I am already Windows 10 Home x64(1890 - OS17763.379)

**Comment by TianZhongJun** [comment]
> I met this problem too.
> I change windows version.
> then it is ok.
> I use this:http://igetintopc.com/windows-10-x64-rs5-october-2018-free-download/
> 
> Which version do u use before u install this package?I am already Windows 10 Home x64(1890 - OS17763.379)

windows 10 pro x64 1809  OS(...),it looks same with you, I forget it.

**Comment by TianZhongJun** [comment]
> I met this problem too.
> I change windows version.
> then it is ok.
> I use this:http://igetintopc.com/windows-10-x64-rs5-october-2018-free-download/
> 
> Which version do u use before u install this package?I am already Windows 10 Home x64(1890 - OS17763.379)

I am now using an older windows versions(OS17763.1)(  download from the link I used post).
everything is ok.

**Comment by Wenzy--** [comment]
> I met this problem too.
> I change windows version.
> then it is ok.
> I use this:http://igetintopc.com/windows-10-x64-rs5-october-2018-free-download/
> Which version do u use before u install this package?I am already Windows 10 Home x64(1890 - OS17763.379)
> 
> I am now using an older windows versions(OS17763.1)(  download from the link I used post).
> everything is ok.

Thanks:) if there's no other way i would have a try.But i think 1890 version is  fit the offical requirements ?what's the difference between them ,is it something they miss?

**Comment by TianZhongJun** [comment]
> I met this problem too.
> I change windows version.
> then it is ok.
> I use this:http://igetintopc.com/windows-10-x64-rs5-october-2018-free-download/
> Which version do u use before u install this package?I am already Windows 10 Home x64(1890 - OS17763.379)
> I am now using an older windows versions(OS17763.1)(  download from the link I used post).
> everything is ok.
> 
> Thanks:) if there's no other way i would have a try.But i think 1890 version is  fit the offical requirements ?what's the difference between them ,is it something they miss?

Sorry, I also don't know about this.

**Comment by ArnoldCarterWong** [comment]
another example console msg of this error:

Shader error in 'HDRP/Lit': Compilation failed [0x80004005 - Unknown error.] 'In file included from :805:
./Packages/com.unity.render-pipelines.high-definition/Runtime/Material/Material.hlsl:6:10: fatal error: 'Packages/com.unity.render-pipelines.core/ShaderLibrary/BSDF.hlsl' file not found
#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/BSDF.hlsl"
         ^
'

Compiling Raytracing program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR

**Comment by smygarn** [comment]
Yes. I've got the same issue. The raytraced shadows on area light doesn't work. It's completely random and flickering when I move the camera! I created a scene with camera, area light, plane and a box. I have RTX 2080 ti, Windows 10 1809 and nvidia 419.67.

**Comment by Wenzy--** [comment]
> I met this problem too.
> I change windows version.
> then it is ok.
> I use this:http://igetintopc.com/windows-10-x64-rs5-october-2018-free-download/

May i ask which window version it is from this link? Home,Education  or Professional

**Comment by FShimomura** [comment]
BRDF.hlsl
ImageBasedLighting.hlsl

there are non-ascii character in those hlsl files.
some guy had copy & paste it from technical papers as comments.

you can find that using below regex:
`[^ -~]`
I just found it in BRDF.hlsl and ImageBasedLighting.hlsl.

1. figure out non-ascii characters then delete it from hlsl files
2. delete "Library" directory
3. open project again

I'm not sure why older windows can work correctly.
anyway, my project was fixed using this method.

**Comment by marunemitsu** [comment]
> BRDF.hlsl
> ImageBasedLighting.hlsl
> 
> there are non-ascii character in those hlsl files.
> some guy had copy & paste it from technical papers as comments.
> 
> you can find that using below regex:
> `[^ -~]`
> I just found it in BRDF.hlsl and ImageBasedLighting.hlsl.
> 
> 1. figure out non-ascii characters then delete it from hlsl files
> 2. delete "Library" directory
> 3. open project again
> 
> I'm not sure why older windows can work correctly.
> anyway, my project was fixed using this method.

Hello, I searched non-ascii characters in BSDF.hlsl and ImageBasedLighting.hlsl with the regex above, but I only found them in comment. Then I deleted "Library" folder but it still doesn't work.
I'm using RS5 1809 home.

**Comment by FShimomura** [comment]
Yes, there are in comment.
BSDF.hlsl 169, 170, 172 and 173
ImageBasedLighting.hlsl 553, 640 and 737

i guess raytrace-shader-compiler confused to parse those lines.

old japanese programmers know comment with non-ascii character can be caused  for compiling error. lol


i have attached modified hlsl files. i hope it help you =)

[modified_files.zip](https://github.com/Unity-Technologies/Unity-Experimental-DXR/files/3201182/modified_files.zip)

**Comment by FShimomura** [comment]
> Hello, I searched non-ascii characters in BSDF.hlsl and ImageBasedLighting.hlsl with the regex above, but I only found them in comment. Then I deleted "Library" folder but it still doesn't work.
> I'm using RS5 1809 home.

Yes, there are in comment.
BSDF.hlsl 169, 170, 172 and 173
ImageBasedLighting.hlsl 553, 640 and 737

i guess raytrace-shader-compiler confused to parse those lines.

old japanese programmers know comment with non-ascii character can be caused  for compiling error. lol

os: Windows 10 Pro(1809 build 17763.503)

i have attached modified hlsl files. i hope it helps you =)

[modified_files.zip](https://github.com/Unity-Technologies/Unity-Experimental-DXR/files/3201182/modified_files.zip)

**Comment by marunemitsu** [comment]
> > Hello, I searched non-ascii characters in BSDF.hlsl and ImageBasedLighting.hlsl with the regex above, but I only found them in comment. Then I deleted "Library" folder but it still doesn't work.
> > I'm using RS5 1809 home.
> 
> Yes, there are in comment.
> BSDF.hlsl 169, 170, 172 and 173
> ImageBasedLighting.hlsl 553, 640 and 737
> 
> i guess raytrace-shader-compiler confused to parse those lines.
> 
> old japanese programmers know comment with non-ascii character can be caused for compiling error. lol
> 
> os: Windows 10 Pro(1809 build 17763.503)
> 
> i have attached modified hlsl files. i hope it helps you =)
> 
> [modified_files.zip](https://github.com/Unity-Technologies/Unity-Experimental-DXR/files/3201182/modified_files.zip)

It finally worked!!!! Thanks! :)
BTW: it makes me realized that I can't use kanji in comment anymore...

**Comment by yaoyutian** [comment]
nice!windows 1903 gpu2070 driver 430.86 ，demo scene indoors runs normally!GPU  consumption nearly 100%。

**Comment by anisunity** [comment]
I am on it

**Comment by sebastienlagarde** [comment]
Thanks for reporting. Anis PR is here:
https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/3929

**Comment by KennethC70** [comment]
Hello all.. I've been going crazy trying to get raytraced shadow work and am very glad I'm not alone..
![image](https://user-images.githubusercontent.com/42198181/65738060-8c8e1880-e11b-11e9-83f7-7eb12dd10511.png)

However, I am as dumb as it comes when it comes to coding, so I really don't know how to fix the non ascii characters on the two files above.  Using wordpad or notepad ++  I can't even "see" any nonusual characters on the comments.. are they visible? or how do I search for them? 

the fix file that someone posted doesn't work for me.  Im using Unity 2019.3b04  and the HDRP from github that has the raytracing for pointlights enabled.

please help.

**Comment by sebastienlagarde** [comment]
Hi, 

Using Notepad++ and inspecting those files with show symbol. I don't see any trouble with characters. So no idea.

Note: We will close this github as it is not used anymore now that DXR is part of beta 2019.3.
The toy scene can be found on another github: https://github.com/Unity-Technologies/SmallOfficeRayTracing
